name: Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: |
          pip install poetry==1.6.1
      - name: Configure Poetry
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}-v1
      - name: Install python dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: |
          poetry install

      - name: Build with PyInstaller
        run: poetry run pyinstaller --onefile ./nuclei_counter/count_nuclei.py
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ (github.event_name == 'push') && github.ref || 'manual-build' }}
          name: Nuclei counter ${{env.GITHUB_REF_NAME}}
          artifacts: "./dist/count_nuclei.exe"
